FROM nginx:alpine

# Copy Nuxt static build
COPY frontend/.output/public /usr/share/nginx/html

# Nginx config
COPY docker/nuxt-nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
